import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
const raw = execFileSync('npx', ['supabase', 'status', '-o', 'json'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
const config = JSON.parse(raw.slice(raw.indexOf('{')));
assert.equal(new URL(config.API_URL).hostname, '127.0.0.1', 'Integration test must target local Supabase');
const client = key => createClient(config.API_URL, key, { auth: { persistSession: false, autoRefreshToken: false } });
const admin = client(config.SERVICE_ROLE_KEY), owner = client(config.ANON_KEY), stranger = client(config.ANON_KEY), mac = client(config.ANON_KEY), tv = client(config.ANON_KEY), anonymous = client(config.ANON_KEY);
const ok = response => { if (response.error) throw new Error(response.error.message); return response.data; };
async function account(c) { const email = `acoustic-${randomUUID()}@example.test`, password = randomUUID(); ok(await admin.auth.admin.createUser({ email, password, email_confirm: true })); ok(await c.auth.signInWithPassword({ email, password })); }
await account(owner); await account(stranger); ok(await mac.auth.signInAnonymously()); ok(await tv.auth.signInAnonymously());
const uid = (await owner.auth.getUser()).data.user.id;
const workspace = ok(await owner.from('workspaces').insert({ name: 'Integration test', owner_id: uid }).select().single()).id;
const paired = ok(await mac.rpc('begin_pairing', { device_name: 'Test Mac', device_kind: 'mac' }));
assert.equal(ok(await mac.from('workspaces').select()).length, 0);
assert.ok((await stranger.rpc('approve_pairing', { w: workspace, code: paired.code })).error);
ok(await owner.rpc('approve_pairing', { w: workspace, code: paired.code }));
assert.ok((await owner.rpc('approve_pairing', { w: workspace, code: paired.code })).error);
const television = ok(await tv.rpc('begin_pairing', { device_name: 'Test TV', device_kind: 'tv' })); ok(await owner.rpc('approve_pairing', { w: workspace, code: television.code }));
const context = { schemaVersion: 1, microphone: 'test', profile: { sampleRate: 48000 } };
const session = ok(await owner.from('measurement_sessions').insert({ workspace_id: workspace, context }).select().single());
const issue = (action, id = randomUUID(), body = {}) => owner.rpc('issue_command', { sid: session.id, target: paired.deviceId, requested_action: action, command_id: id, body });
assert.ok((await issue('start')).error);
const commandId = randomUUID(), prepare = ok(await issue('prepare', commandId)); assert.equal(ok(await issue('prepare', commandId)).id, prepare.id);
assert.ok((await tv.rpc('ack_command', { cid: prepare.id, response: { ready: true } })).error);
ok(await mac.rpc('ack_command', { cid: prepare.id, response: { ready: true } }));
assert.ok((await issue('start')).error, 'Missing captureReady must never arm playback');
const start = ok(await issue('start', randomUUID(), { captureReady: true })); ok(await mac.rpc('ack_command', { cid: start.id, response: { playing: true } })); ok(await owner.rpc('renew_lease', { cid: start.id }));
assert.ok((await stranger.rpc('renew_lease', { cid: start.id })).error);
ok(await issue('stop')); assert.ok((await owner.rpc('renew_lease', { cid: start.id })).error);
assert.equal(ok(await stranger.from('commands').select()).length, 0);
const artifact = ok(await owner.from('artifacts').insert({ workspace_id: workspace, session_id: session.id, kind: 'capture' }).select().single());
assert.ok((await owner.rpc('finalize_artifact', { aid: artifact.id, info: {} })).error);
const path = `${workspace}/${artifact.id}/000000.f32`, bytes = Buffer.alloc(32768 * 4), digest = createHash('sha256').update(bytes).digest('hex');
assert.ok((await stranger.storage.from('acoustic-artifacts').upload(path, bytes)).error);
ok(await owner.storage.from('acoustic-artifacts').upload(path, bytes));
const manifest = { schemaVersion: 1, context, encoding: 'float32-le', sampleRate: 48000, frames: 32768, complete: true, parts: [{ index: 0, path, bytes: bytes.length, frames: 32768, sha256: digest }] };
assert.ok((await owner.rpc('finalize_artifact', { aid: artifact.id, info: { ...manifest, frames: 1 } })).error);
assert.ok((await owner.rpc('finalize_artifact', { aid: artifact.id, info: { ...manifest, context: {} } })).error);
ok(await owner.rpc('finalize_artifact', { aid: artifact.id, info: manifest })); ok(await owner.rpc('finalize_artifact', { aid: artifact.id, info: manifest }));
assert.equal(ok(await owner.from('analysis_jobs').select().eq('artifact_id', artifact.id)).length, 1);
assert.ok((await tv.rpc('claim_analysis', { d: television.deviceId })).error);
assert.equal(ok(await tv.from('artifacts').select().eq('id', artifact.id)).length, 0);
assert.ok((await anonymous.storage.from('acoustic-artifacts').download(path)).error);
ok(await mac.storage.from('acoustic-artifacts').download(path));
const job = ok(await mac.rpc('claim_analysis', { d: paired.deviceId }))[0]; assert.equal(job.artifact_id, artifact.id);
assert.ok((await mac.rpc('finish_analysis', { jid: job.id, result_data: {}, failure: null })).error);
ok(await mac.rpc('finish_analysis', { jid: job.id, result_data: null, failure: 'Synthetic empty PCM has no timing markers' }));
assert.equal(ok(await owner.from('artifacts').select('status').eq('id', artifact.id).single()).status, 'invalid');
const receiverId = randomUUID();
assert.ok((await tv.rpc('register_avr', { r: receiverId, d: television.deviceId, receiver_name: 'Denied TV' })).error);
ok(await mac.rpc('register_avr', { r: receiverId, d: paired.deviceId, receiver_name: 'Test AVR' }));
assert.equal(ok(await tv.from('avr_receivers').select()).length, 0);
assert.equal(ok(await stranger.from('avr_receivers').select()).length, 0);
const observation = { r: receiverId, at_time: new Date().toISOString(), rev: 'a'.repeat(64), observation: { schemaVersion: 1, errors: {} } };
assert.ok((await owner.rpc('observe_avr', observation)).error);
ok(await mac.rpc('observe_avr', observation));
const avrCommand = { r: receiverId, operation_id: randomUUID(), rev: 'a'.repeat(64), action: 'volume-up', payload: {} };
assert.ok((await tv.rpc('issue_avr_operation', avrCommand)).error);
assert.ok((await mac.rpc('issue_avr_operation', avrCommand)).error);
assert.ok((await owner.rpc('issue_avr_operation', { ...avrCommand, rev: 'b'.repeat(64) })).error);
const avrOperation = ok(await owner.rpc('issue_avr_operation', avrCommand));
assert.equal(ok(await owner.rpc('issue_avr_operation', avrCommand)).id, avrOperation.id);
assert.equal(Date.parse(avrOperation.expires_at) - Date.parse(avrOperation.created_at), 10000);
assert.ok((await owner.rpc('finish_avr_operation', { operation_id: avrOperation.id, response: { status: 'succeeded' } })).error);
ok(await mac.rpc('finish_avr_operation', { operation_id: avrOperation.id, response: { status: 'unknown' } }));
ok(await mac.rpc('finish_avr_operation', { operation_id: avrOperation.id, response: { status: 'succeeded' } }));
assert.equal(ok(await owner.from('avr_operations').select().eq('id', avrOperation.id).single()).outcome.status, 'unknown');
const snapshotId = randomUUID(), rawPath = `${receiverId}/${snapshotId}.json`;
ok(await mac.from('avr_snapshots').insert({ id: snapshotId, receiver_id: receiverId, purpose: 'diagnostic', state: {}, revision: 'a'.repeat(64), raw_path: rawPath }));
ok(await mac.storage.from('avr-private').upload(rawPath, '{}', { contentType: 'application/json' }));
assert.ok((await tv.storage.from('avr-private').download(rawPath)).error);
ok(await owner.storage.from('avr-private').download(rawPath));
const unassigned = client(config.ANON_KEY); ok(await unassigned.auth.signInAnonymously());
const otherMac = ok(await unassigned.rpc('begin_pairing', { device_name: 'Other Mac', device_kind: 'mac' }));
ok(await owner.rpc('approve_pairing', { w: workspace, code: otherMac.code }));
assert.equal(ok(await unassigned.from('avr_receivers').select()).length, 0);
assert.ok((await unassigned.rpc('observe_avr', observation)).error);
console.log('PASS: AVR owner/assigned-Mac isolation, TV and unrelated Mac denial, 10-second expiry, revision guard, idempotent outcomes, private raw storage');
ok(await owner.rpc('revoke_device', { d: paired.deviceId }));
assert.ok((await mac.rpc('device_heartbeat', { d: paired.deviceId })).error);
assert.ok((await mac.rpc('observe_avr', observation)).error);
assert.ok((await owner.rpc('issue_avr_operation', { ...avrCommand, operation_id: randomUUID() })).error);
assert.equal(ok(await mac.from('measurement_sessions').select()).length, 0);
console.log('PASS: owner/device isolation, one-time pairing, idempotency, readiness, leases, storage ACL, manifest integrity, worker access, revocation');
